### ISSUE TITLE
Cannot add weight 

### ISSUE THREAD

**Issue by MrDragon420** [OllisGit/OctoPrint-SpoolManager#131] opened 2021-02-23 23:59 UTC
Cannot add weights

**Comment by thirschbuechler** [comment] 2021-04-13 15:44
yes you can

**Comment by thirschbuechler** [comment] 2021-04-13 16:07
probably duplicate of #123 and #142

**Comment by OllisGit** [comment] 2021-04-18 07:36
closed, becuse no detailed information. So my assumption (as thirschbuechler) it is related to dialog-layout-issue (see #142)

**Closed by OllisGit** 2021-04-18 07:36 UTC
